server:
  port: 3000


# local docker run
# docker run --name tp-back-app -d -it -e MYSQL_ROOT_PASSWORD=1234 -p 3308:3306 mysql
#  docker exec -it tp-back-app /bin/bash
#  mysql -u root -p
# create user 'tp-back-app'@'localhost' identified by '1234'
# 모든 디비 권한 부여
# grant all privileges on *.* to 'tp-back-app'@'localhost';
# create schema `tp-back-app`

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TP-BACK-APP-MYSQL-DEV-URI}:${TP-BACK-APP-MYSQL-DEV-PORT}/${TP-BACK-APP-MYSQL-SCHEMA}?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${TP-BACK-APP-USER-NAME}
    password: ${TP-BACK-APP-USER-PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true # 로그에 ddl,dml 표시
        format_sql: true # 쿼리 들여쓰기
        use_sql_comments: true # 주석 표시

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: trace # 바인딩 파라미터 확인